[project]
name = "homework"
version = "0.1.0"
description = "FastAPI service"
authors = [{ name = "Gao Qi Sheng" }]
dependencies = [
    "fastapi>=0.120.0",
    "uvicorn>=0.38.0",
    "scikit-learn == 1.6.1",
]
